### ISSUE TITLE
Ability to configure data sending

### ISSUE THREAD

**Issue by Felix14-v2** [kb-1000/no-telemetry#1]
Great thanks for this mod!
Are there any plans to add the ability to configure the sending data to make it partial or even with the content that the user sets? (for example, comic messages to microsoft)

**Comment by kb-1000** [comment]
Well... I honestly don't know how the telemetry endpoint or Microsoft/Mojang would react to something like that, but I wouldn't expect anything good.
This is doable (using a mixin plugin to conditionally enable one set of mixins or another set of mixins), although I don't know if that's a good idea...
