### ISSUE TITLE
Remove Telemetry Data Button in 1.19.3

### ISSUE THREAD

**Issue by ghost** [kb-1000/no-telemetry#12]

**Comment by Xetaxheb** [comment]
and.. the telemetry

**Comment by ghost** [comment]
Well, the telemetry is already removed in the mod. I am just talking about the button itself.

**Comment by kb-1000** [comment]
As long as the mod runs at all and doesn't spam mixin warnings, telemetry is gone.
As for the button, I'll have to look into that.

**Comment by Felix14-v2** [comment]
> As for the button, I'll have to look into that.

1.19.3 has a [hidden "none" state](https://crowdin.com/translate/minecraft/10038/enus-engb?filter=basic&value=0#q=telemetry%20state)  for telemetry sending, so maybe you can just unhide it?

UPD: ough, Debugify has already done this
![Screenshot_20221208-165650](https://user-images.githubusercontent.com/75726196/206465093-e8fc4f01-0e48-4c48-85c0-257ae15fd00b.jpg)
