### ISSUE TITLE
Environment confusion when Connector is installed

### ISSUE THREAD

**Issue by EnderTurret** [kb-1000/no-telemetry#16]
Basically, No Telemetry (1.7.0) gets confused and thinks it's running on Fabric when [Connector](https://modrinth.com/mod/connector) (1.0.0-beta.28+1.20.1) and [Forgified Fabric API](https://modrinth.com/mod/forgified-fabric-api) (0.90.7+1.10.3+1.20.1) are installed. [Here's](https://gist.github.com/EnderTurret/3d967228b3164c9fdbe8e38d17d0af74) a log file (notice the `Error loading class: ` messages from Mixin).

I believe this happens because `CommonUtil` [checks to see if a Fabric loader class doesn't exist](https://github.com/kb-1000/no-telemetry/blob/main/src/main/java/de/kb1000/notelemetry/CommonUtil.java#L5) as one of the conditions for running on Forge, which is not the case when Connector is installed. In my testing I wrote [a coremod](https://gist.github.com/EnderTurret/b4e04184c7d0c7a5d8207be9ce65f370) to verify that this is the problem (by replacing the contents of that method with a `return true;`) and that appeared to fix the issue, as the missing class messages no longer appeared.

**Comment by kb-1000** [comment]
Sounds like my initial suspicion and of course _unanswered_ question was right and connector does mess this kinda mod up. Sorry, but I'm not going to be special-casing and workaround it, I'd consider this an issue on their side since they cause it.

**Comment by kb-1000** [comment]
Also worth noting that thanks to my fairly aggressive fallback, telemetry is still successfully disabled thanks to the authlib mixin, as you can see in the log.
