### ISSUE TITLE
Publish to CurseForge

### ISSUE THREAD

**Issue by Madis0** [kb-1000/no-telemetry#2]
What happened to https://www.curseforge.com/minecraft/mc-mods/no-telemetry/ ? I recall it being available there.

Considering that Mojang does not intend to add a toggle for this and 1.18 is nearing, it would be great to include this mod in modpacks.

**Comment by Felix14-v2** [comment]
No Telemetry still available on Modrinth: https://modrinth.com/mod/no-telemetry

**Comment by kb-1000** [comment]
I did upload it to Curseforge, and that page does exist, but you can't access it because it hasn't been approved. As far as I understand, the description isn't detailed enough, and I haven't changed that yet.

**Comment by Madis0** [comment]
Seems to be accepted in CF.

**Comment by Madis0** [comment]
Please now mark the file as 1.18-compatible so it can be listed for inclusion in modpacks :)

Also make sure to enable this if you haven't yet (off by default for new projects):
![image](https://user-images.githubusercontent.com/8611110/144487181-068819f5-e8d4-4534-b6fa-b378beb180ea.png)

**Comment by kb-1000** [comment]
I actually created the mod page long enough ago that this toggle wasn't even announced back then.
I marked 1.1.0 and 1.2.0 as compatible with 1.18 release.
