### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by ichordev** [kb-1000/no-telemetry#7]
Seems like the new version and the mod are incompatible. Possibly updates to the telemetry system?

**Comment by kb-1000** [comment]
It works fine on 1.18.2 over here.
As such, it's rather likely one of your other mods doesn't support 1.18.2, or otherwise interferes with this mod.
However, please upload log/crash report.

**Comment by Oondanomala** [comment]
If it works consider adding the 1.18.2 tag for Curseforge

**Comment by kb-1000** [comment]
In case you still have problems with this mod on 1.18.2, please create a new issue with logs attached.
